personalwebsite/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path(
        'blog/<int:pk>',
        views.PostDetailView.as_view(),
        name='post_detail'
    ),
    path(
        'blog/<slug:category_slug>/',
        views.CategoryPostListView.as_view(),
        name='category_posts'
    ),
    path('blog/', views.PostListView.as_view(), name='all_posts'),
]

personalwebsite/mainpage/urls.py
from django.urls import path

from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.main, name='main'),
]

personalwebsite/personalwebsite/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('', include('blog.urls')),
    path('', include('portfolio.urls')),
    path('', include('mainpage.urls')),
)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

personalwebsite/portfolio/urls.py
from django.urls import path

from . import views

app_name = 'portfolio'

urlpatterns = [
    path(
        'portfolio/<int:pk>',
        views.PortfolioDetailView.as_view(),
        name='project_detail'
    ),
    path(
        'portfolio/<slug:category_slug>/',
        views.CategoryProjectListView.as_view(),
        name='category_projects'
    ),
    path(
        'portfolio/',
        views.PortfolioListView.as_view(),
        name='all_projects'
    ),
]

personalwebsite/templates/includes/blog_sidebar.html
<div class="p-4 mb-3 bg-body-tertiary rounded">
  <h4 class="fst-italic">About</h4>
  <p class="mb-0">
    Hi! My name is Alexander and I am a python developer.
    Here I write about programming and life. I really hope that you will find something interesting for yourself.
  </p>
</div>

<div>
  <h4 class="fst-italic">Recent posts</h4>
  <ul class="list-unstyled">
    {% for post in page_obj.posts|slice:":3" %}
      <li>
        <a class="d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top" href="{% url 'blog:post_detail' post.id %}">
          <img class="bd-placeholder-img" src="{{ post.main_foto.url }}" alt="" style="object-fit: cover;" height="150" width="100">
          <div class="col-lg-8">
            <h6 class="mb-0">{{ post.name }}</h6>
            <small class="text-body-secondary">{{ post.pub_date }}</small>
          </div>
        </a>
      </li>
    {% endfor %}
  </ul>
</div>

<!-- <div class="p-4">
  <h4 class="fst-italic">Archives</h4>
  <ol class="list-unstyled mb-0">
    <li><a href="#">March 2021</a></li>
    <li><a href="#">February 2021</a></li>
    <li><a href="#">January 2021</a></li>
    <li><a href="#">December 2020</a></li>
    <li><a href="#">November 2020</a></li>
    <li><a href="#">October 2020</a></li>
    <li><a href="#">September 2020</a></li>
    <li><a href="#">August 2020</a></li>
    <li><a href="#">July 2020</a></li>
    <li><a href="#">June 2020</a></li>
    <li><a href="#">May 2020</a></li>
    <li><a href="#">April 2020</a></li>
  </ol>
</div>

<div class="p-4">
  <h4 class="fst-italic">Elsewhere</h4>
  <ol class="list-unstyled">
    <li><a href="#">GitHub</a></li>
    <li><a href="#">Twitter</a></li>
    <li><a href="#">Facebook</a></li>
  </ol>
</div> -->

personalwebsite/templates/includes/contact_badges.html
{% load static %}
<div class="col py-1">
  <a class="link-underline-light link-underline-opacity-50" href="https://t.me/aleksandr_buchelnikov">
    <span class="badge d-flex align-items-center p-1 pe-2 text-info-emphasis bg-info-subtle border border-info-subtle rounded-pill">
      <img src="{% static 'img/badges/icons8-telegram-48.png' %}" alt="Описание" width="25" height="25" class="ms-1 me-1">Telegram
    </span>
  </a>
</div>
<div class="col py-1">
  <a class="link-underline-light link-underline-opacity-50" href="https://www.linkedin.com/in/aleksandr-buchelnikov/">
    <span class="badge d-flex align-items-center p-1 pe-2 text-info-emphasis bg-info-subtle border border-info-subtle rounded-pill">
      <img src="{% static 'img/badges/icons8-linkedin-48.png' %}" alt="Описание" width="25" height="25" class="ms-1 me-1">LinkedIn
    </span>
  </a>
</div>
<div class="col py-1">
  <a class="link-underline-light link-underline-opacity-50" href="mailto:al.buchelnikov@gmail.com">
    <span class="badge d-flex align-items-center p-1 pe-2 text-info-emphasis bg-info-subtle border border-info-subtle rounded-pill">
      <img src="{% static 'img/badges/icons8-gmail-48.png' %}" alt="Описание" width="25" height="25" class="ms-1 me-1">E-Mail
    </span>
  </a>
</div>
<div class="col py-1">
  <a class="link-underline-light link-underline-opacity-50" href="https://github.com/AVanslov">
    <span class="badge d-flex align-items-center p-1 pe-2 text-info-emphasis bg-info-subtle border border-info-subtle rounded-pill">
      <img src="{% static 'img/badges/icons8-github-24.png' %}" alt="Описание" width="25" height="25" class="ms-1 me-1">GitHub
    </span>
  </a>
</div>

personalwebsite/templates/includes/download_cv_dropdown.html
<div class="dropdown d-inline-flex p-1">
  <button class="btn btn btn-outline-primary me-2 dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    Download CV
  </button>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="https://drive.google.com/file/d/1U1KjtNHtK_9114gSC7B8LGmepUXZtZSx/view?usp=sharing">In English CV in Europass format</a></li>
    <li><a class="dropdown-item" href="https://drive.google.com/file/d/1Pzw_JekdR3nWsk8E32Cvw1TFJzPH7uxl/view?usp=sharing">In Russian CV in HH format</a></li>
  </ul>
</div>

personalwebsite/templates/includes/footer.html
{% load static %}
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
      </a>
      <span class="mb-3 mb-md-0 text-body-secondary">&copy; 2024 Buchelnikov Aleksandr</span>
    </div>

    <div class="row d-flex gap-2 justify-content-md-end py-3 text-start">
      {% include "includes/contact_badges.html" %}
    </div>
  </footer>
</div>

personalwebsite/templates/includes/header.html
{% load static %}
{% load i18n %}
<div class="container">
  <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <div class="col-md-3 mb-2 mb-md-0">
      <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-braces" viewBox="0 0 16 16">
          <path d="M2.114 8.063V7.9c1.005-.102 1.497-.615 1.497-1.6V4.503c0-1.094.39-1.538 1.354-1.538h.273V2h-.376C3.25 2 2.49 2.759 2.49 4.352v1.524c0 1.094-.376 1.456-1.49 1.456v1.299c1.114 0 1.49.362 1.49 1.456v1.524c0 1.593.759 2.352 2.372 2.352h.376v-.964h-.273c-.964 0-1.354-.444-1.354-1.538V9.663c0-.984-.492-1.497-1.497-1.6M13.886 7.9v.163c-1.005.103-1.497.616-1.497 1.6v1.798c0 1.094-.39 1.538-1.354 1.538h-.273v.964h.376c1.613 0 2.372-.759 2.372-2.352v-1.524c0-1.094.376-1.456 1.49-1.456V7.332c-1.114 0-1.49-.362-1.49-1.456V4.352C13.51 2.759 12.75 2 11.138 2h-.376v.964h.273c.964 0 1.354.444 1.354 1.538V6.3c0 .984.492 1.497 1.497 1.6"/>
        </svg>
      </a>
    </div>

    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
      <li><a href="{% url 'mainpage:main' %}" class="nav-link px-2 link-secondary">Home</a></li>
      <li><a href="{% url 'portfolio:all_projects' %}" class="nav-link px-2">Portfolio</a></li>
      <li><a href="{% url 'blog:all_posts' %}" class="nav-link px-2">Blog</a></li>
    </ul>

    <div class="col-md-4 col-lg-3 text-end text-end">
      {% include 'includes/hire_me_dropdown.html' %}
      {% include 'includes/language_choice.html' %}
      <!-- <button type="button" class="btn btn-outline-primary me-2 disabled">Order website</button>
      <button type="button" class="btn btn-primary">Hire me</button> -->
    </div>
  </header>
</div>

personalwebsite/templates/includes/language_choice.html
{% load i18n %}
{% get_current_language as current_language %}
{% get_available_languages as languages %}
{% with request.resolver_match.view_name as view_name %}
  <div class="dropdown d-inline-flex">
    <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      {{ current_language }}
    </button>
    <ul class="dropdown-menu">
      {% for lang_code, lang_name in languages %}
        {% language lang_code %}
          <li><a class="dropdown-item" href="{% url 'mainpage:main' %}">{{ lang_code }}</a></li>
        {% endlanguage %}
      {% endfor %}
    </ul>
  </div>
{% endwith %}

personalwebsite/templates/includes/multiselect_filter.html
<form action="" method="get">
  <div class="row align-items-center pb-5 py-1">
    <div class="col-11">
      <div class="row">
        {% for i in filterset.form %}
          {% for i in i %}
            <div class="col form-check form-check-inline">
              <!-- <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1"> -->
              <span class="badge d-flex align-items-center p-2 pl-5 text-primary-emphasis bg-primary-subtle border border-primary-subtle rounded-3">
                {{ i }}
              </span>
            </div>
          {% endfor %}
        {% endfor %}
      </div>
    </div>
    <div class="col-1">
      <button class="btn btn-primary" type="submit">Search</button>
    </div>  
  </div>
</form>

personalwebsite/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

personalwebsite/templates/includes/post_card.html
{% load static %}
<div class="col">
  <a class="link-underline-light link-underline-opacity-50" href="{% url 'blog:post_detail' post.id %}">
    <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url('{{ MEDIA_URL }}{{ post.main_foto }}');">
      <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
        <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">{{ post.name }}</h3>
        <ul class="d-flex list-unstyled mt-auto">
          <li class="me-auto">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-braces" viewBox="0 0 16 16">
              <path d="M2.114 8.063V7.9c1.005-.102 1.497-.615 1.497-1.6V4.503c0-1.094.39-1.538 1.354-1.538h.273V2h-.376C3.25 2 2.49 2.759 2.49 4.352v1.524c0 1.094-.376 1.456-1.49 1.456v1.299c1.114 0 1.49.362 1.49 1.456v1.524c0 1.593.759 2.352 2.372 2.352h.376v-.964h-.273c-.964 0-1.354-.444-1.354-1.538V9.663c0-.984-.492-1.497-1.497-1.6M13.886 7.9v.163c-1.005.103-1.497.616-1.497 1.6v1.798c0 1.094-.39 1.538-1.354 1.538h-.273v.964h.376c1.613 0 2.372-.759 2.372-2.352v-1.524c0-1.094.376-1.456 1.49-1.456V7.332c-1.114 0-1.49-.362-1.49-1.456V4.352C13.51 2.759 12.75 2 11.138 2h-.376v.964h.273c.964 0 1.354.444 1.354 1.538V6.3c0 .984.492 1.497 1.497 1.6"/>
            </svg>
          </li>
          <li class="d-flex align-items-center me-3">
            <small>{{ post.category }}</small>
          </li>
          <li class="d-flex align-items-center">
            <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg>
            <small>{{ post.pub_date|date:"d E Y" }}</small>
          </li>
        </ul>
      </div>
    </div>
  </a>
</div>

personalwebsite/templates/includes/preloader.html
<div class="preloader">
  <svg class="preloader__image" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
    <path fill="currentColor"
      d="M304 48c0 26.51-21.49 48-48 48s-48-21.49-48-48 21.49-48 48-48 48 21.49 48 48zm-48 368c-26.51 0-48 21.49-48 48s21.49 48 48 48 48-21.49 48-48-21.49-48-48-48zm208-208c-26.51 0-48 21.49-48 48s21.49 48 48 48 48-21.49 48-48-21.49-48-48-48zM96 256c0-26.51-21.49-48-48-48S0 229.49 0 256s21.49 48 48 48 48-21.49 48-48zm12.922 99.078c-26.51 0-48 21.49-48 48s21.49 48 48 48 48-21.49 48-48c0-26.509-21.491-48-48-48zm294.156 0c-26.51 0-48 21.49-48 48s21.49 48 48 48 48-21.49 48-48c0-26.509-21.49-48-48-48zM108.922 60.922c-26.51 0-48 21.49-48 48s21.49 48 48 48 48-21.49 48-48-21.491-48-48-48z">
    </path>
  </svg>
</div>

personalwebsite/templates/includes/project_card.html
{% load static %}
<div class="col">
  <a class="link-underline-light link-underline-opacity-50" href="{% url 'portfolio:project_detail' post.id %}">
    <div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg" style="background-image: url('{{ MEDIA_URL }}{{ post.main_foto }}');">
      <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
        <h3 class="pt-5 mt-5 mb-4 display-6 lh-1 fw-bold">{{ post.name }}</h3>
        <ul class="d-flex list-unstyled mt-auto">
          <li class="me-auto">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-braces" viewBox="0 0 16 16">
              <path d="M2.114 8.063V7.9c1.005-.102 1.497-.615 1.497-1.6V4.503c0-1.094.39-1.538 1.354-1.538h.273V2h-.376C3.25 2 2.49 2.759 2.49 4.352v1.524c0 1.094-.376 1.456-1.49 1.456v1.299c1.114 0 1.49.362 1.49 1.456v1.524c0 1.593.759 2.352 2.372 2.352h.376v-.964h-.273c-.964 0-1.354-.444-1.354-1.538V9.663c0-.984-.492-1.497-1.497-1.6M13.886 7.9v.163c-1.005.103-1.497.616-1.497 1.6v1.798c0 1.094-.39 1.538-1.354 1.538h-.273v.964h.376c1.613 0 2.372-.759 2.372-2.352v-1.524c0-1.094.376-1.456 1.49-1.456V7.332c-1.114 0-1.49-.362-1.49-1.456V4.352C13.51 2.759 12.75 2 11.138 2h-.376v.964h.273c.964 0 1.354.444 1.354 1.538V6.3c0 .984.492 1.497 1.497 1.6"/>
            </svg>
          </li>
          <li class="d-flex align-items-center me-3">
            <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#geo-fill"/></svg>
            {% for tag in post.technologies_id.all|slice:":3" %} 
              <small>
                <img src="{{ tag.badge.url }}" width="30" height="30">
              </small>
            {% endfor %}
          </li>
          <li class="d-flex align-items-center">
            <svg class="bi me-2" width="1em" height="1em"><use xlink:href="#calendar3"/></svg>
            <small>{{ post.pub_date|date:"d E Y" }}</small>
          </li>
        </ul>
      </div>
    </div>
  </a>
</div>

personalwebsite/templates/includes/tag.html
{% load static %}
<div class="col text-center mx-auto" style="max-width: 150px;">
  <a class="link-underline-light link-underline-opacity-50" href="{% url 'portfolio:category_projects' tag.slug %}">
    <span class="badge d-flex align-items-center p-1 pe-2 text-info-emphasis bg-info-subtle border border-info-subtle rounded-pill">
      <img src="{{ tag.badge.url }}" alt="Описание" width="25" height="25" class="ms-1 me-1">{{ tag.name }}
    </span>
  </a>
</div>

personalwebsite/templates/includes/toggle-theme.html
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
  <symbol id="check2" viewBox="0 0 16 16">
    <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
  </symbol>
  <symbol id="circle-half" viewBox="0 0 16 16">
    <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
  </symbol>
  <symbol id="moon-stars-fill" viewBox="0 0 16 16">
    <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
    <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
  </symbol>
  <symbol id="sun-fill" viewBox="0 0 16 16">
    <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
  </symbol>
</svg>
<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
  <button class="btn btn-outline-primary py-2 dropdown-toggle d-flex align-items-center"
    id="bd-theme"
    type="button"
    aria-expanded="false"
    data-bs-toggle="dropdown"
    aria-label="Toggle theme (auto)">
    <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
    <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
  </button>
  <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
    <li>
      <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
        <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
        Light
        <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
      </button>
    </li>
    <li>
      <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
        <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
        Dark
        <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
      </button>
    </li>
    <li>
      <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
        <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
        Auto
        <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
      </button>
    </li>
  </ul>
</div>

personalwebsite/templates/includes/yandex_metrica.html
<!-- Yandex.Metrika counter -->
<script type="text/javascript" >
    (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
    m[i].l=1*new Date();
    for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
    k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
    (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
 
    ym(97785738, "init", {
         clickmap:true,
         trackLinks:true,
         accurateTrackBounce:true,
         webvisor:true
    });
 </script>
 <noscript><div><img src="https://mc.yandex.ru/watch/97785738" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
 <!-- /Yandex.Metrika counter -->