personalwebsite/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path(
        'blog/<int:pk>',
        views.PostDetailView.as_view(),
        name='post_detail'
    ),
    path(
        'blog/<slug:category_slug>/',
        views.CategoryPostListView.as_view(),
        name='category_posts'
    ),
    path('blog/', views.PostListView.as_view(), name='all_posts'),
]

personalwebsite/personalwebsite/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('', include('blog.urls')),
    path('', include('portfolio.urls')),
    path('', include('mainpage.urls')),
)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

personalwebsite/blog/models.py
from django.db import models

MAXIMUM_STRING_LENGTH = 256

NUMBER_OF_VISIBLE_CHATACTERS = 15


class TitleModel(models.Model):
    """Модель абстрактного класса Заголовок."""

    name = models.CharField('Заголовок', max_length=MAXIMUM_STRING_LENGTH,)

    class Meta:
        abstract = True


class Category(TitleModel):
    """Модель таблицы Категория."""

    description = models.TextField('Описание')
    slug = models.SlugField(
        'Идентификатор',
        unique=True,
        max_length=64,
        help_text=(
            'Идентификатор страницы для URL; разрешены символы латиницы, '
            'цифры, дефис и подчёркивание.'
        ),
    )

    def __str__(self):
        return self.name[:NUMBER_OF_VISIBLE_CHATACTERS]


class Post(TitleModel):
    """Модель таблицы Публикация."""

    text = models.TextField('Текст')
    pub_date = models.DateTimeField(
        'Дата и время публикации',
        help_text=(
            'Если установить дату и время в будущем'
            ' — можно делать отложенные публикации.'
        )
    )
    category = models.ForeignKey(
        Category,
        verbose_name='Категория',
        on_delete=models.SET_NULL,
        null=True,
    )
    main_foto = models.ImageField(
        'Фото',
        upload_to='post_images',
        blank=True,
    )

    class Meta:
        verbose_name = 'публикация'
        verbose_name_plural = 'Публикации'
        default_related_name = 'posts'
        ordering = ('-pub_date',)

    def __str__(self):
        return self.name[:NUMBER_OF_VISIBLE_CHATACTERS]

personalwebsite/blog/views.py
import markdown
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView

from .models import Category, Post


class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'page_obj'

    def converter_to_markdown_content(self, posts):
        md = markdown.Markdown(extensions=["fenced_code", "tables"])
        all_posts = []
        for post in posts:
            post.text = md.convert(post.text)
            all_posts.append(post)
        return all_posts

    def get_queryset(self):
        queryset = {
            'posts': self.converter_to_markdown_content(
                posts=Post.objects.order_by('pub_date').all()
            ),  # добавить пагинацию
            'categories': Category.objects.order_by('name').all()
        }
        return queryset


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'

    def get_post(self):
        return get_object_or_404(
            Post,
            id=self.kwargs['pk']
        )

    def converter_to_markdown_content(self):
        post = self.get_post()
        md = markdown.Markdown(extensions=["fenced_code", "tables"])
        post.text = md.convert(post.text)
        return post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = self.converter_to_markdown_content()
        return context


class CategoryPostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'page_obj'

    def converter_to_markdown_content(self, posts):
        md = markdown.Markdown(extensions=["fenced_code", "tables"])
        all_posts = []
        for post in posts:
            post.text = md.convert(post.text)
            all_posts.append(post)
        return all_posts

    def get_category(self):
        return get_object_or_404(
            Category,
            slug=self.kwargs['category_slug']
        )

    def get_queryset(self):
        queryset = {
            'posts': self.converter_to_markdown_content(
                posts=self.get_category().posts.all()
            ),
            'categories': Category.objects.order_by('name').all()
        }
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.get_category()
        return context

personalwebsite/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{ post.name }}
{% endblock %}
{% block content %}
<div class="container">
  <div class="container my-5">
    <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
        <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
          <h1 class="display-4 fw-bold lh-1 text-body-emphasis">{{ post.name }}</h1>
          <p class="lead">{{ post.category }}</p>
          <p class="blog-post-meta">{{post.pub_date}} by <a>Aleksandr Buchelnikov</a></p>
        </div>
        <div class="col-lg-4 offset-lg-1 p-0 overflow-hidden shadow-lg">
            <img class="rounded-lg-3 rounded-top-3" src="{{ post.main_foto.url }}" alt="" style="object-fit: cover;" height="250" width="500">
        </div>
    </div>
  </div>

  <div class="row g-5">
    <div class="col-md-8">

      <article class="blog-post">
        <p>{{ post.text|safe }}</p>
      </article>

    </div>
  </div>
</div>
{% endblock %}

personalwebsite/templates/blog/post_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Blog
{% endblock %}
{% block content %}
  {% include "includes/toggle-theme.html" %}
  {% with request.resolver_match.view_name as view_name %}
    <div class="container">

      <div class="nav-scroller py-1 mb-3 border-bottom">
        <nav class="nav nav-underline justify-content-between">
          {% for category in page_obj.categories %}
            <a class="nav-item nav-link link-body-emphasis {% if category.slug in request.path %} active {% endif %}" href="{% url 'blog:category_posts' category.slug %}">{{ category.name }}</a>
          {% endfor %}
        </nav>
      </div>
    </div>
    
    <div class="container">
      <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
        <div class="col-lg-6 px-0">
          {% with page_obj.posts|first as first_post %}
            {% if view_name == 'blog:category_posts' and page_obj.posts|length == 0 %}
              <h1 class="display-4 fst-italic">
                В данной категории пока нет статей
              </h1>
            {% else %}
              <h1 class="display-4 fst-italic">
                {{ first_post.name }}
              </h1>
              <p class="lead my-3">{{ first_post.text|truncatechars:100|safe }}</p>
              <p class="lead mb-0"><a href="{% url 'blog:post_detail' first_post.id %}" class="text-body-emphasis fw-bold">Continue reading...</a></p>
            {% endif %}
          {% endwith %}
        </div>
      </div>
      {% if page_obj.posts|length > 1 %}
        <div class="row mb-2">
          {% for post in page_obj.posts|slice:"0:5" %}
          <div class="col-md-6">
            <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
              <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-primary-emphasis">{{ post.category }}</strong>
                <h3 class="mb-0">{{ post.name }}</h3>
                <div class="mb-1 text-body-secondary">{{ post.pub_date }}</div>
                <a href="{% url 'blog:post_detail' post.id %}" class="icon-link gap-1 icon-link-hover stretched-link">
                  Continue reading
                  <svg class="bi"><use xlink:href="#chevron-right"/></svg>
                </a>
              </div>
              <div class="col-auto d-none d-lg-block">
                <img class="bd-placeholder-img" src="{{ post.main_foto.url }}" alt="" style="object-fit: cover;" height="200" width="200">
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      {% endif %}
      
      <div class="row g-5">
        <div class="col-md-8">
          {% if page_obj.posts|length > 0 %}
            <h3 class="pb-4 mb-4 fst-italic border-bottom">
              Fresh
            </h3>
            {% for post in page_obj.posts|slice:"0:5" %}
              <article class="blog-post">
                <h2 class="display-5 link-body-emphasis mb-1">{{ post.name }}</h2>
                <p class="blog-post-meta">{{post.pub_date}} by <a href="#">Aleksandr Buchelnikov</a></p>
                <p>{{ post.text|safe }}</p>
              </article>
            {% endfor %}
            <!-- <nav class="blog-pagination" aria-label="Pagination">
              <a class="btn btn-outline-primary rounded-pill" href="#">Older</a>
              <a class="btn btn-outline-secondary rounded-pill disabled" aria-disabled="true">Newer</a>
            </nav> -->
          {% endif %}
        </div>
        
        <div class="col-md-4">
          <div class="position-sticky" style="top: 2rem;">
            {% include "includes/blog_sidebar.html" %}
          </div>
        </div>
      </div>
    </div>
  {% endwith %}
{% endblock %}